apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: apply-manifests
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: MANIFEST_DIR
        description: The directory in source that contains yaml manifests
        type: string
        default: "k8s"

  steps:
    - name: apply
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Applying manifests in $(inputs.params.MANIFEST_DIR) directory
          oc apply -f $(inputs.params.MANIFEST_DIR)
          echo -----------------------------------
